/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import connection.Myconnection;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A19B45923
 */
public class frm_inventario extends javax.swing.JFrame {
    
      DefaultTableModel productos; 

    /**
     * Creates new form frm_inventario
     */
    public frm_inventario() {
        initComponents();
        
        this.productos = (DefaultTableModel) tbl_productos.getModel();
        Mostrardatos("");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
       
    }
    
    public void RefrescarTabla(){
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
        productos.setColumnCount(0);
        productos.setRowCount(0);
        tbl_productos.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_inventario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        txt_buscador = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_nom = new javax.swing.JTextField();
        txt_proveedor = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        txt_des = new javax.swing.JTextField();
        txt_pre = new javax.swing.JTextField();
        txt_codpr = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_inventario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_inventario.setText("Inventario");
        getContentPane().add(lbl_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 144, -1));

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_productos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 100, 599, 247));

        txt_buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscadorActionPerformed(evt);
            }
        });
        txt_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscadorKeyPressed(evt);
            }
        });
        getContentPane().add(txt_buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, 232, -1));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 59, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 40, 161, -1));
        jPanel1.add(txt_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 86, 161, -1));
        jPanel1.add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 136, 161, -1));
        jPanel1.add(txt_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 179, 161, -1));
        jPanel1.add(txt_pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 40, 240, -1));
        jPanel1.add(txt_codpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 86, 240, -1));
        jPanel1.add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 136, 86, -1));

        jLabel1.setText("Nombrepro:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 40, -1, -1));

        jLabel2.setText("Proveedor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 89, -1, -1));

        jLabel3.setText("Stock:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 139, -1, -1));

        jLabel4.setText("Descripcion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 182, -1, -1));

        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 43, -1, -1));

        jLabel6.setText("codigopro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 89, -1, -1));

        jLabel7.setText("tipoproducto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 139, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 100, 640, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_buscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorKeyPressed
        // TODO add your handling code here:
          try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String B = txt_buscador.getText()+"";
        Mostrardatos(B);
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        
    }    
    }//GEN-LAST:event_txt_buscadorKeyPressed

    private void txt_buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscadorActionPerformed

    private void tbl_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productosMouseClicked
        // TODO add your handling code here:
                
        try{
  
            String nom = (String)productos.getValueAt(tbl_productos.getSelectedRow(), 1);
            String pro = (String)productos.getValueAt(tbl_productos.getSelectedRow(), 2);
            String stock = (String)productos.getValueAt(tbl_productos.getSelectedRow(), 3);
            String des = (String)productos.getValueAt(tbl_productos.getSelectedRow(),4);
            String pre = (String)productos.getValueAt(tbl_productos.getSelectedRow(),5);
            String cod = (String)productos.getValueAt(tbl_productos.getSelectedRow(),6);
            String tipo = (String)productos.getValueAt(tbl_productos.getSelectedRow(),7);
                 
            
                    
            txt_nom.setText(nom);
            txt_proveedor.setText(pro);
            txt_stock.setText(stock);
            txt_des.setText(des);
            txt_pre.setText(pre);
            txt_codpr.setText(cod);
             txt_tipo.setText(tipo);
           
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,"error"+ex);
        }
      
    
    }//GEN-LAST:event_tbl_productosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_inventario;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTextField txt_buscador;
    private javax.swing.JTextField txt_codpr;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_pre;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables

    public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            Myconnection cc=new Myconnection();
            Connection cn=Myconnection.getConnection();
            RefrescarTabla();
            productos.addColumn("idproducto");
            productos.addColumn("nombre");
            productos.addColumn("proveedor");
            productos.addColumn("stock");
            productos.addColumn("descripcion");
            productos.addColumn("precio");
            productos.addColumn("codigopro");
            productos.addColumn("tipoproducto");
            
            
            this.tbl_productos.setModel(productos);
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM productos";
            }
            else{
            sql="SELECT * FROM productos WHERE nombre like '"+valor+"%'" ;
            } 

            String []datos=new String [8];
            
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            datos[6]=rs.getString(7);
            datos[7]=rs.getString(8);
            
            
           
            
            productos.addRow(datos);
            }
            tbl_productos.setModel(productos);
            }catch(SQLException ex){
            Logger.getLogger(frm_inventario.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }

   
        
   
    }
    

       
    
    
         

