/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.*;

/**
 *
 * @author maxim
 */
public class frm_insert_clients extends javax.swing.JFrame {

    /**
     *
     */
    public frm_insert_clients() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgk_panel = new javax.swing.JPanel();
        frm_bkg_panel = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        txt_apellido = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        lbl_balance = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        cbb_tipo = new javax.swing.JComboBox<>();
        btn_limpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar clientes");
        setResizable(false);

        bgk_panel.setBackground(new java.awt.Color(10, 103, 193));
        bgk_panel.setMaximumSize(new java.awt.Dimension(1600, 900));

        frm_bkg_panel.setBackground(new java.awt.Color(255, 255, 255));
        frm_bkg_panel.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        frm_bkg_panel.setMaximumSize(new java.awt.Dimension(1500, 800));
        frm_bkg_panel.setMinimumSize(new java.awt.Dimension(1500, 800));
        frm_bkg_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        lbl_title.setText("Insertar Clientes");
        frm_bkg_panel.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 45, -1, 87));

        txt_nombre.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        frm_bkg_panel.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 240, 510, 40));

        btn_insert.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        btn_insert.setText("Insertar");
        frm_bkg_panel.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 675, 240, 45));

        txt_apellido.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        frm_bkg_panel.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 345, 510, 40));

        txt_balance.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        frm_bkg_panel.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 450, 510, 40));

        txt_tipo.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        frm_bkg_panel.add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 555, 240, 40));

        lbl_nombre.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_nombre.setText("Nombre");
        frm_bkg_panel.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 240, -1, -1));

        lbl_apellido.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_apellido.setText("Apellido");
        frm_bkg_panel.add(lbl_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 345, -1, -1));

        lbl_balance.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_balance.setText("Balance");
        frm_bkg_panel.add(lbl_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 450, -1, -1));

        lbl_tipo.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_tipo.setText("Tipo de cliente");
        frm_bkg_panel.add(lbl_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 555, -1, -1));

        cbb_tipo.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        cbb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Otro..." }));
        frm_bkg_panel.add(cbb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 555, 240, 45));

        btn_limpiar.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        frm_bkg_panel.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 675, 240, 45));

        jPanel1.setBackground(new java.awt.Color(232, 122, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgk_panelLayout = new javax.swing.GroupLayout(bgk_panel);
        bgk_panel.setLayout(bgk_panelLayout);
        bgk_panelLayout.setHorizontalGroup(
            bgk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgk_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(frm_bkg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(bgk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgk_panelLayout.createSequentialGroup()
                    .addGap(0, 791, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        bgk_panelLayout.setVerticalGroup(
            bgk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgk_panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(frm_bkg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(bgk_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgk_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgk_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        String name = txt_nombre.getText();
        String sname = txt_apellido.getText();
        String balance = txt_balance.getText();
        String tipo = txt_tipo.getText();
        String c_tipo = cbb_tipo.getItemAt(cbb_tipo.getSelectedIndex());

        ver_limpiar mf = new ver_limpiar();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_insert_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_insert_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_insert_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_insert_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_insert_clients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgk_panel;
    private javax.swing.JButton btn_insert;
    public javax.swing.JButton btn_limpiar;
    public static javax.swing.JComboBox<String> cbb_tipo;
    public static javax.swing.JPanel frm_bkg_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_title;
    public static javax.swing.JTextField txt_apellido;
    public static javax.swing.JTextField txt_balance;
    public static javax.swing.JTextField txt_nombre;
    public static javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
